version: '3.8'
services:
  telegraf:
    image: telegraf:1.26-alpine
#    environment:
#      - HOST_VAR=/var/run/utmp
    volumes:
      - C:/Users/User/Desktop/loadqa-homeworks/2.Load environment/samples/telegraf:/etc/telegraf
      - C:/Users/User/Desktop/loadqa-homeworks/2.Load environment/samples/telegraf/telegraf.conf/:/etc/telegraf/telegraf.conf:ro
#      - C:/Users/User/Desktop/loadqa-homeworks/2.Load environment/samples/var/run/utmp:/var/run/utmp
#      - C:/Users/User/Desktop/loadqa-homeworks/2.Load environment/samples/rootfs:/rootfs:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - "8125:8125"
    networks:
      - teleg

  influxdb:
    image: influxdb:1.8.10-alpine
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - teleg

  grafana:
    image: grafana/grafana:8.3.3
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/ # https://grafana.com/grafana/dashboards/928
    networks:
      - teleg

volumes:
  grafana_data: { }
  influxdb_data: { }

networks:
  teleg: